FROM python:3.12-slim

WORKDIR /usr/src/app

COPY requirements.txt requirements-dev.txt ./

RUN pip install --no-cache-dir -r requirements.txt -r requirements-dev.txt

COPY . .

ENV DATABASE_URL=sqlite+aiosqlite:///:memory:

CMD ["pytest"]

# docker build -f Dockerfile.test -t weather-app-test .
# docker run --rm weather-app-test